## Lab 1: Data in Python

The data for this activity can be downloaded here (under "Data Sets"): https://www.statlearning.com/resources-python

As a first step, create a folder in this location called "data" and drop the Credit.csv file in that location.

If you open the ".gitignore" file, you'll notice that one of the entries is "data" so that your data files will not be shared on GitHub.

In [5]:
import pandas as pd
import numpy as np
Credit = pd.read_csv('data/Credit.csv')
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

### What are the feature names?

In [6]:
Credit.columns

Index(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Own',
       'Student', 'Married', 'Region', 'Balance'],
      dtype='object')

### What are the data types of the feature values (i.e., numeric, categorical)

In [7]:
Credit.dtypes

Income       float64
Limit          int64
Rating         int64
Cards          int64
Age            int64
Education      int64
Own           object
Student       object
Married       object
Region        object
Balance        int64
dtype: object

### Find the mean, median, and mode of the feature "Age."

In [8]:
# mean
Credit['Age'].mean()

np.float64(55.6675)

In [9]:
# median
Credit['Age'].median()

np.float64(56.0)

In [10]:
# mode
Credit['Age'].mode()[0]

np.int64(44)

### Create a subset of Credit that only contains the columns Age, Region, and Income. Call it "Subset."

In [11]:
Subset = Credit[['Age', 'Region', 'Income']]
Subset

     Age Region   Income
0     34  South   14.891
1     82   West  106.025
2     71   West  104.593
3     36   West  148.924
4     68  South   55.882
..   ...    ...      ...
395   32  South   12.096
396   65   East   13.364
397   67  South   57.872
398   44  South   37.728
399   64   West   18.701

[400 rows x 3 columns]

### From this subset, create two partitions: 
- One that contains records for Ages below 50, and one that contains Ages 50+
- Call them "Younger" and "Older"

In [42]:
Younger = Subset[Subset['Age'] < 50]

In [43]:
Older = Subset[Subset['Age'] >= 50]

### Use these partitions to compare the mean and median Income for each age group (less than 50 vs. 50+)

In [49]:
# mean of younger
Younger['Income'].mean()

np.float64(41.65203726708074)

In [46]:
# mean of older
Older['Income'].mean()

np.float64(47.6216569037657)

In [35]:
# median of younger
Younger['Income'].median()

np.float64(31.861)

In [34]:
# median of older
Older['Income'].median()

np.float64(33.694)

### What does the difference between mean and median suggest about the distribution of income?

#The difference between the mean and median suggests that the distribution of income is right-skewed or positively skewed across both age groups, as the mean is higher than the median. This indicates that a smal number of high earners are pulling the overall average upward, while most individuals earn closer to the lower median values.

### What are the possible values for Region?

In [ ]:
Credit['Region'].unique()

array(['South', 'West', 'East'], dtype=object)

### Use the value_counts method to build a frequency table for the possible values of Region.

In [19]:
Credit['Region'].value_counts()

Region
South    199
West     102
East      99
Name: count, dtype: int64

### Compare the average income for students vs. non-students.

In [20]:
students = Credit[Credit['Student'] == 'Yes']

In [21]:
non_students = Credit[Credit['Student'] == 'No']

In [22]:
# average income for students
students['Income'].mean()

np.float64(47.29205)

In [23]:
# average income for non-students
non_students['Income'].mean()

np.float64(44.988533333333336)

Often, banks will use a variable called _utilization_ to assess credit risk.
Utilization is the ratio of balance to limit (i.e., what % of the credit limit is being used?)
### Add a feature to the Credit dataset to measure utilization

Credit['Utilization'] = Credit['Balance'] / Credit['Limit']

In [25]:
Credit.head()

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance,Utilization
0,14.891,3606,283,2,34,11,No,No,Yes,South,333,0.092346
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903,0.135892
2,104.593,7075,514,4,71,11,No,No,No,West,580,0.081979
3,148.924,9504,681,3,36,11,Yes,No,No,West,964,0.101431
4,55.882,4897,357,2,68,16,No,No,Yes,South,331,0.067592

### What is the maximum utilization value in this set?

In [26]:
Credit['Utilization'].max()

np.float64(0.27693008426326576)